{% set version = "0.1.post" %}
{% set commit = "d7845fcd8b8a06248e42ca083c6460c43723c154" %}

package:
  name: arrow-cpp
  version: {{ version }}


source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/apache/arrow/archive/{{ commit }}.tar.gz
  sha256: 5ac7a3cdddb4d856ab7534cbe7c5ab5c5a69daaebb1f24c141f0aaf01b2dc099

build:
  number: 5
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - boost 1.62.*
    - flatbuffers
    - cmake

test:
  commands:
    - test -f $PREFIX/lib/libarrow.a  # [unix]
    - test -f $PREFIX/lib/libarrow.so  # [linux]
    - test -f $PREFIX/lib/libarrow_io.so  # [linux]
    - test -f $PREFIX/lib/libarrow_ipc.so  # [linux]
    - test -f $PREFIX/lib/libarrow.dylib  # [osx]
    - test -f $PREFIX/lib/libarrow_io.dylib  # [osx]
    - test -f $PREFIX/lib/libarrow_ipc.dylib  # [osx]

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  summary: 'C++ libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
