{% set version = "0.1.post" %}
{% set commit = "61a54f8a619efc4fd256c446be29905d6484c5e9" %}

package:
  name: arrow-cpp
  version: {{ version }}


source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/apache/arrow/archive/{{ commit }}.tar.gz
  sha256: d07cdd9c04df9542a2fd9266009e3b1721bffb2fabce953adbcb2fcd8a11a320

build:
  number: 10
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - boost 1.63.*
    - flatbuffers
    - cmake
    - jemalloc

  run:
    - jemalloc


test:
  commands:
    - test -f $PREFIX/lib/libarrow.a  # [unix]
    - test -f $PREFIX/lib/libarrow.so  # [linux]
    - test -f $PREFIX/lib/libarrow_io.a  # [unix]
    - test -f $PREFIX/lib/libarrow_io.so  # [linux]
    - test -f $PREFIX/lib/libarrow_ipc.a  # [unix]
    - test -f $PREFIX/lib/libarrow_ipc.so  # [linux]
    - test -f $PREFIX/lib/libarrow_jemalloc.so  # [linux]
    - test -f $PREFIX/lib/libarrow.dylib  # [osx]
    - test -f $PREFIX/lib/libarrow_io.dylib  # [osx]
    - test -f $PREFIX/lib/libarrow_ipc.dylib  # [osx]
    - test -f $PREFIX/lib/libarrow_jemalloc.dylib  # [osx]

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  summary: 'C++ libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
