{% set version = "0.3.0.post" %}
{% set commit = "ff72951f0262ea230f7cfbb2f4c97ea7cf70845b" %}

package:
  name: arrow-cpp
  version: {{ version }}


source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/apache/arrow/archive/{{ commit }}.tar.gz
  sha256: 44eecc4ebd735d160aa1f6010416113d7dd0385312a5badfc105cf545241aa7a

build:
  number: 2
  skip: true  # [win32]
  skip: true  # [win and py<35]
  features:
    - vc14  # [win and py>=35]

requirements:
  build:
    - toolchain
    - boost 1.63.*
    - flatbuffers
    - rapidjson
    - cmake
    - jemalloc  # [unix]
    - python
    - numpy x.x

  run:
    - jemalloc  # [unix]
    - boost 1.63.*  # [win]
    - python
    - numpy x.x
    - vc 14  # [win and py>=35]

test:
  commands:
    - test -f $PREFIX/lib/libarrow.a  # [unix]
    - test -f $PREFIX/lib/libarrow.so  # [linux]
    - test -f $PREFIX/lib/libarrow_python.so  # [linux]
    - test -f $PREFIX/lib/libarrow_jemalloc.so  # [linux]
    - test -f $PREFIX/lib/libarrow.dylib  # [osx]
    - test -f $PREFIX/lib/libarrow_python.dylib  # [osx]
    - test -f $PREFIX/lib/libarrow_jemalloc.dylib  # [osx]
    - if not exist %LIBRARY_INC%\\arrow\\api.h exit 1               # [win]
    - if not exist %PREFIX%\\Library\\bin\\arrow.dll exit 1         # [win]
    - if not exist %PREFIX%\\Library\\bin\\arrow_python.dll exit 1  # [win]

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  summary: 'C++ libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - leifwalsh
    - jreback
    - cpcloud
