{% set version = "0.17.0" %}
{% set filename = "apache-arrow-" + version + ".tar.gz" %}
{% set checksum = "2c46b4c3e1f88aad510214e633a6f4ce459708f3db78cd0daf549a135cbe8e6d" %}

package:
  name: arrow-cpp
  version: {{ version }}

source:
  fn: {{ filename }}
  url: https://dist.apache.org/repos/dist/release/arrow/arrow-{{ version }}/{{ filename }}
  sha256: {{ checksum }}

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage("arrow-cpp", max_pin="x.x.x") }}

requirements:
  build:
    - cmake 3.16.*
    - autoconf  # [unix]
    - ninja
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - aws-sdk-cpp
    - boost-cpp
    - brotli
    - bzip2
    - c-ares
    - gflags
    - glog
    - grpc-cpp
    - libprotobuf
    - clangdev 8.*
    - llvmdev 8.*
    - lz4-c
    - numpy 1.16.*
    - orc  # [unix]
    - python
    - rapidjson
    - re2
    - snappy
    - thrift-cpp >=0.11
    - zlib
    - zstd

  run:
    - {{ pin_compatible('numpy', lower_bound='1.16') }}
    - aws-sdk-cpp
    - boost-cpp
    - brotli
    - c-ares
    - gflags
    - glog
    - grpc-cpp
    - lz4-c
    - python
    - re2
    - snappy
    - zlib
    - zstd

test:
  commands:
    # headers
    - test -f $PREFIX/include/arrow/api.h              # [unix]
    - test -f $PREFIX/include/arrow/flight/types.h     # [unix]
    - test -f $PREFIX/include/plasma/client.h          # [unix]
    - test -f $PREFIX/include/gandiva/engine.h         # [unix and not (aarch64 or ppc64le)]
    - test -f $PREFIX/include/parquet/api/reader.h     # [unix]
    - if not exist %LIBRARY_INC%\\arrow\\api.h exit 1            # [win]
    - if not exist %LIBRARY_INC%\\gandiva\\engine.h exit 1       # [win]
    - if not exist %LIBRARY_INC%\\parquet\\api\\reader.h exit 1  # [win]

    # shared
    - test -f $PREFIX/lib/libarrow.so            # [linux]
    - test -f $PREFIX/lib/libarrow_dataset.so    # [linux]
    - test -f $PREFIX/lib/libarrow_flight.so     # [linux]
    - test -f $PREFIX/lib/libarrow_python.so     # [linux]
    - test -f $PREFIX/lib/libparquet.so          # [linux]
    - test -f $PREFIX/lib/libgandiva.so          # [linux and not (aarch64 or ppc64le)]
    - test -f $PREFIX/lib/libplasma.so           # [linux]
    - test -f $PREFIX/lib/libarrow.dylib          # [osx]
    - test -f $PREFIX/lib/libarrow_dataset.dylib  # [osx]
    - test -f $PREFIX/lib/libarrow_python.dylib   # [osx]
    - test -f $PREFIX/lib/libgandiva.dylib        # [osx]
    - test -f $PREFIX/lib/libparquet.dylib        # [osx]
    - test -f $PREFIX/lib/libplasma.dylib         # [osx]
    - if not exist %PREFIX%\\Library\\bin\\arrow.dll exit 1          # [win]
    - if not exist %PREFIX%\\Library\\bin\\arrow_dataset.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\arrow_flight.dll exit 1   # [win]
    - if not exist %PREFIX%\\Library\\bin\\arrow_python.dll exit 1   # [win]
    - if not exist %PREFIX%\\Library\\bin\\parquet.dll exit 1        # [win]
    - if not exist %PREFIX%\\Library\\bin\\gandiva.dll exit 1        # [win]

    # absence of static libraries
    - test ! -f $PREFIX/lib/libarrow.a          # [unix]
    - test ! -f $PREFIX/lib/libarrow_dataset.a  # [unix]
    - test ! -f $PREFIX/lib/libarrow_flight.a   # [unix]
    - test ! -f $PREFIX/lib/libarrow_python.a   # [unix]
    - test ! -f $PREFIX/lib/libplasma.a         # [unix]
    - test ! -f $PREFIX/lib/libparquet.a        # [unix]
    - test ! -f $PREFIX/lib/libgandiva.a        # [unix]
    - if exist %PREFIX%\\Library\\lib\\arrow_static.lib exit 1          # [win]
    - if exist %PREFIX%\\Library\\lib\\arrow_dataset_static.lib exit 1  # [win]
    - if exist %PREFIX%\\Library\\lib\\arrow_flight_static.lib exit 1   # [win]
    - if exist %PREFIX%\\Library\\lib\\arrow_python_static.lib exit 1   # [win]
    - if exist %PREFIX%\\Library\\lib\\parquet_static.lib exit 1        # [win]
    - if exist %PREFIX%\\Library\\lib\\gandiva_static.lib exit 1        # [win]

    # conda tools
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME   # [osx]

about:
  home: http://github.com/apache/arrow
  license: Apache-2.0
  license_file:
    - LICENSE.txt
  summary: C++ libraries for Apache Arrow

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - leifwalsh
    - jreback
    - cpcloud
    - pcmoritz
    - robertnishihara
    - siddharthteotia
    - kou
    - kszucs
    - pitrou
    - nealrichardson
