{% set version = "0.1.post" %}
{% set commit = "e70d97dbc8dc86161083e94c45d5828f79211f6b" %}

package:
  name: arrow-cpp
  version: {{ version }}


source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/apache/arrow/archive/{{ commit }}.tar.gz
  sha256: 4e22ccf441237232fb19b64aeae442474d9a6a6173bec3d7f868e6ba00ae9660

build:
  number: 3
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - boost 1.62.*
    - flatbuffers
    - cmake

test:
  commands:
    - test -f $PREFIX/lib/libarrow.a  # [unix]
    - test -f $PREFIX/lib/libarrow.so  # [linux]
    - test -f $PREFIX/lib/libarrow_io.so  # [linux]
    - test -f $PREFIX/lib/libarrow_ipc.so  # [linux]
    - test -f $PREFIX/lib/libarrow.dylib  # [osx]
    - test -f $PREFIX/lib/libarrow_io.dylib  # [osx]
    - test -f $PREFIX/lib/libarrow_ipc.dylib  # [osx]

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  summary: 'C++ libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
