{% set version = "0.1.pre" %}
{% set commit = "772800ace3706b8f169803b3ef8932e04ec54619" %}

package:
  name: arrow-cpp
  version: {{ version }}


source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/apache/arrow/archive/{{ commit }}.tar.gz
  sha256: 01ff68b9ab2785cc2a465fedc62536faab4ff461b6d42b9b00df15bb2e41dfa5

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - boost
    - flatbuffers
    - cmake

test:
  commands:
    - test -f $PREFIX/lib/libarrow.so  # [linux]
    - test -f $PREFIX/lib/libarrow.dylib  # [osx]

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  summary: 'C++ libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
