{% set version = "0.1.post" %}
{% set commit = "446ec9bd628244bf675887f5a030d3a94c07645e" %}

package:
  name: arrow-cpp
  version: {{ version }}


source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/apache/arrow/archive/{{ commit }}.tar.gz
  sha256: 8f1be3e9094c2d0cbf22859709fd4e6b1659a8ea763c428ed5f4209ee1f22d9e

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - boost 1.61.*
    - flatbuffers
    - cmake

test:
  commands:
    - test -f $PREFIX/lib/libarrow.a  # [unix]
    - test -f $PREFIX/lib/libarrow.so  # [linux]
    - test -f $PREFIX/lib/libarrow_io.so  # [linux]
    - test -f $PREFIX/lib/libarrow_ipc.so  # [linux]
    - test -f $PREFIX/lib/libarrow.dylib  # [osx]
    - test -f $PREFIX/lib/libarrow_io.dylib  # [osx]
    - test -f $PREFIX/lib/libarrow_ipc.dylib  # [osx]

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  summary: 'C++ libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
