{% set version = "0.11.1" %}
{% set filename = "apache-arrow-" + version + ".tar.gz" %}
{% set checksum = "c524f3d47f0cdb7445c0326b20e79f60485e12daeb2adc8ad6a845ad6c19c1ac" %}

package:
  name: arrow-cpp
  version: {{ version }}

source:
  fn: {{ filename }}
  url: https://dist.apache.org/repos/dist/release/arrow/arrow-{{ version }}/{{ filename }}
  sha256: {{ checksum }}

build:
  number: 1000
  skip: true  # [win32]
  skip: true  # [win and py<35]
  features:
    - vc14  # [win and py>=35]

requirements:
  build:
    - cmake
    - autoconf  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - boost-cpp
    - thrift-cpp >=0.11
    - libprotobuf
    - flatbuffers
    - rapidjson
    - zlib
    - glog
    - snappy
    - brotli
    - zstd
    - lz4-c
    - python
    - numpy 1.14.*

  run:
    - boost-cpp
    - python
    - {{ pin_compatible('numpy', lower_bound='1.14') }}
    - snappy  # [win and py>=35]
    - zlib

test:
  commands:
    # headers
    - test -f $PREFIX/include/arrow/api.h              # [unix]
    - test -f $PREFIX/include/plasma/client.h          # [unix]
    - test -f $PREFIX/include/parquet/api/reader.h     # [unix]
    - if not exist %LIBRARY_INC%\\arrow\\api.h exit 1            # [win]
    - if not exist %LIBRARY_INC%\\parquet\\api\\reader.h exit 1  # [win]

    # static
    - test -f $PREFIX/lib/libarrow.a         # [unix]
    - test -f $PREFIX/lib/libarrow_python.a  # [unix]
    - test -f $PREFIX/lib/libparquet.a       # [unix]
    - test -f $PREFIX/lib/libplasma.a        # [unix]
    - if not exist %PREFIX%\\Library\\lib\\arrow_static.lib exit 1         # [win]
    - if not exist %PREFIX%\\Library\\lib\\arrow_python_static.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\parquet_static.lib exit 1       # [win]

    # shared
    - test -f $PREFIX/lib/libarrow.so            # [linux]
    - test -f $PREFIX/lib/libarrow_python.so     # [linux]
    - test -f $PREFIX/lib/libparquet.so          # [linux]
    - test -f $PREFIX/lib/libplasma.so           # [linux]
    - test -f $PREFIX/lib/libarrow.dylib         # [osx]
    - test -f $PREFIX/lib/libarrow_python.dylib  # [osx]
    - test -f $PREFIX/lib/libparquet.dylib       # [osx]
    - test -f $PREFIX/lib/libplasma.dylib        # [osx]
    - if not exist %PREFIX%\\Library\\bin\\arrow.dll exit 1         # [win]
    - if not exist %PREFIX%\\Library\\bin\\arrow_python.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\parquet.dll exit 1       # [win]

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  summary: 'C++ libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - leifwalsh
    - jreback
    - cpcloud
    - pcmoritz
    - robertnishihara
    - siddharthteotia
    - kou
    - kszucs
    - pitrou
