{% set version = "0.5.0.pre" %}
{% set commit = "b4d34f8fde52df14f087cedcca8b7276b5cf0697" %}

package:
  name: arrow-cpp
  version: {{ version }}


source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/apache/arrow/archive/{{ commit }}.tar.gz
  sha256: 0d3b9bfbfb4c4024542191694d8a469949ce02367e3034499a2d3c15e3f85c2f

build:
  number: 2
  skip: true  # [win32]
  skip: true  # [win and py<35]
  features:
    - vc14  # [win and py>=35]

requirements:
  build:
    - toolchain
    - cmake
    - boost-cpp 1.63.*
    - flatbuffers
    - rapidjson
    - zlib 1.2.*
    - snappy
    - brotli
    - zstd
    - lz4-c
    - jemalloc 4.4.0  # [unix]
    - python
    - numpy x.x

  run:
    - jemalloc 4.4.0  # [unix]
    - python
    - numpy x.x
    - vc 14  # [win and py>=35]

test:
  commands:
    - test -f $PREFIX/lib/libarrow.a  # [unix]
    - test -f $PREFIX/lib/libarrow.so  # [linux]
    - test -f $PREFIX/lib/libarrow_python.so  # [linux]
    - test -f $PREFIX/lib/libarrow.dylib  # [osx]
    - test -f $PREFIX/lib/libarrow_python.dylib  # [osx]
    - if not exist %LIBRARY_INC%\\arrow\\api.h exit 1               # [win]
    - if not exist %PREFIX%\\Library\\bin\\arrow.dll exit 1         # [win]
    - if not exist %PREFIX%\\Library\\bin\\arrow_python.dll exit 1  # [win]

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  summary: 'C++ libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - leifwalsh
    - jreback
    - cpcloud
