{% set version = "0.1.post" %}
{% set commit = "7ac320bde52ae47007dadac7398e22a203c6a48d" %}

package:
  name: arrow-cpp
  version: {{ version }}


source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/apache/arrow/archive/{{ commit }}.tar.gz
  sha256: 5c56af26b31c4054cdfe424e11e02055e42badb549d46eae0773aed35a1d9d84

build:
  number: 11
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - boost 1.63.*
    - flatbuffers
    - cmake
    - jemalloc  # [unix]

  run:
    - jemalloc  # [unix]


test:
  commands:
    - test -f $PREFIX/lib/libarrow.a  # [unix]
    - test -f $PREFIX/lib/libarrow.so  # [linux]
    - test -f $PREFIX/lib/libarrow_io.a  # [unix]
    - test -f $PREFIX/lib/libarrow_io.so  # [linux]
    - test -f $PREFIX/lib/libarrow_ipc.a  # [unix]
    - test -f $PREFIX/lib/libarrow_ipc.so  # [linux]
    - test -f $PREFIX/lib/libarrow_jemalloc.so  # [linux]
    - test -f $PREFIX/lib/libarrow.dylib  # [osx]
    - test -f $PREFIX/lib/libarrow_io.dylib  # [osx]
    - test -f $PREFIX/lib/libarrow_ipc.dylib  # [osx]
    - test -f $PREFIX/lib/libarrow_jemalloc.dylib  # [osx]

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  summary: 'C++ libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
