# linux_ppc64le is explicitly removed again, see https://github.com/conda-forge/arrow-cpp-feedstock/issues/143
provider: {linux_aarch64: default, linux_ppc64le: azure, win: azure}
conda_forge_output_validation: true
