bot:
  abi_migration_branches: [0.17.x, 1.0.x, 2.0.x]
build_platform: {linux_aarch64: linux_64, linux_ppc64le: linux_64, osx_arm64: osx_64}
conda_forge_output_validation: true
provider: {linux_aarch64: default, linux_ppc64le: default}
test_on_native_only: true
