appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: L4wnYQ//dRfl6aNxwNSSaL2Lg1cksNzF1PBvuqfGb3J3JD8IDq/1sRMWFmwAS64kLFGvJ7/v9WAiCSuNOUcs+X56Ur5YDyyJqega09gVSy65REmNgeeUPx6/mgdr3dIFs3gCxqzn2L0DMKq7ZViAVq0U1HncU5e9DhGCq+aypyAOATEhlyZ2IGbEKea3w5VaFSi3fkJMzUaFhtvPQEakLoWB5MS6sFxYRfD0HK2JlS49MZiYfGmEEnY/bUx7m6Q/jQvCz1qBlgjmWsfkwz+RVZ1mkMBWoB4a7N6GzGQb9u645kAQS7jYm7ZJ+c3XmuXwYB7VkjwCQBYRrVjsHH2iroApcrEMhclYRE+WgIuKdJHg+SMjwVH1XmanFeGuQ0djUgDD5shvmqka2229V1jBFgjZJJRszHwbLeBWKwYS9vI56NHNsS+8GCpLNlA4NqKXaC8vxqOeUijRv/JMCdTsNy8CBz98O8pKY01FGARiEGrcaIvKOicI9YY6b/zrmFqGJa+RclOgMgkbrJoarl18Hk+ldL+pULoeVa1Un2G1ZyP6PtvnFI7v7uGInc3VfGf7b/gaZcOsrbTWRqwziXhGpv515rY9LCWKPNE6bPjKQweTYKUqeKoybMJGKG/MzG0Q3fRu6OH+1+CD1idXHmGgP8+Lk4hRwsSYWAZT9IeqbmM=}
