bot:
  abi_migration_branches:
  - 1.0.x
  - 2.0.x
  - 3.0.x
  - 4.0.x
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_forge_output_validation: true
test_on_native_only: true
