azure:
  free_disk_space: true
  settings_linux:
    swapfile_size: 8GiB
  settings_win:
    variables:
      CONDA_BLD_PATH: C:\\bld\\
      MINIFORGE_HOME: C:\\Miniforge
bot:
  abi_migration_branches:
  - 21.x
  - 20.x
  - 19.x
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
# DO NOT MERGE
conda_forge_output_validation: false
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
test: native_and_emulated
