azure:
  # see conda-forge/arrow-cpp-feedstock#825;
  # manually distributed to ensure we have:
  # max_parallel(linux) >= #{jobs for aarch/ppc}
  max_parallel: 31
bot:
  abi_migration_branches:
  - 3.0.x
  - 4.0.x
  - 5.0.x
  - 6.0.x
  - 7.0.x
build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
test_on_native_only: true
