azure:
  max_parallel: 20
bot:
  abi_migration_branches:
  - 6.0.x
  - 7.0.x
  - 8.0.x
build_platform:
  linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
test_on_native_only: true
