bot:
  abi_migration_branches:
  - 20.x
  - 19.x
  - 18.x
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
test: native_and_emulated
workflow_settings:
  build_workspace_dir:
    - value: C:\bld
      os: win
  free_disk_space:
    - value: quick
      os: linux
  tools_install_dir:
    - value: C:\Miniforge
      os: win
