bot:
  abi_migration_branches:
  - 3.0.x
  - 4.0.x
  - 5.0.x
  - 6.0.x
  - 7.0.x
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test_on_native_only: true
